version: '3.4'

services:
  differencedb:
    container_name: differencedb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
 
  diff.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DifferenceConnectionString=Server=differencedb;Database=DifferenceDb;"  

    depends_on:
       - differencedb
    ports:
       - "8000:80"


  


